//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttrContents
    {
        public AttrContents()
        {
            this.NavCatagories = new HashSet<NavCatagories>();
            this.Products = new HashSet<Products>();
        }
    
        public int ID { get; set; }
        public int TitleID { get; set; }
        public string Content { get; set; }
    
        public virtual AttrTitles AttrTitles { get; set; }
        public virtual ICollection<NavCatagories> NavCatagories { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
