//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttrTitles
    {
        public AttrTitles()
        {
            this.AttrContents = new HashSet<AttrContents>();
            this.FiltCatagories = new HashSet<FiltCatagories>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<AttrContents> AttrContents { get; set; }
        public virtual ICollection<FiltCatagories> FiltCatagories { get; set; }
    }
}
