//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.CartProducts = new HashSet<CartProducts>();
        }
    
        public int ID { get; set; }
        public int CustomersID { get; set; }
    
        public virtual ICollection<CartProducts> CartProducts { get; set; }
    }
}
