//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiltCatagories
    {
        public FiltCatagories()
        {
            this.SubFiltCatas = new HashSet<FiltCatagories>();
            this.AttrTitles = new HashSet<AttrTitles>();
            this.Products = new HashSet<Products>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<FiltCatagories> SubFiltCatas { get; set; }
        public virtual FiltCatagories ParentFiltCata { get; set; }
        public virtual ICollection<AttrTitles> AttrTitles { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
