//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiltCatagories
    {
        public FiltCatagories()
        {
            this.SubFiltCatas = new HashSet<FiltCatagories>();
            this.AttrTitles = new HashSet<AttrTitles>();
            this.Products = new HashSet<Products>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<FiltCatagories> SubFiltCatas { get; set; }
        public virtual FiltCatagories ParentFiltCata { get; set; }
        public virtual ICollection<AttrTitles> AttrTitles { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
