//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavCatagories
    {
        public NavCatagories()
        {
            this.SubNavCatas = new HashSet<NavCatagories>();
            this.AttrContents = new HashSet<AttrContents>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> FiltCatagoryID { get; set; }
        public bool IsSubnav { get; set; }
    
        public virtual FiltCatagories FiltCatagories { get; set; }
        public virtual ICollection<NavCatagories> SubNavCatas { get; set; }
        public virtual NavCatagories ParentNavCata { get; set; }
        public virtual ICollection<AttrContents> AttrContents { get; set; }
    }
}
