//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavCatagories
    {
        public NavCatagories()
        {
            this.SubNavCatas = new HashSet<NavCatagories>();
            this.AttrContents = new HashSet<AttrContents>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> FiltCatagoryID { get; set; }
        public bool IsSubnav { get; set; }
    
        public virtual FiltCatagories FiltCatagories { get; set; }
        public virtual ICollection<NavCatagories> SubNavCatas { get; set; }
        public virtual NavCatagories ParentNavCata { get; set; }
        public virtual ICollection<AttrContents> AttrContents { get; set; }
    }
}
