//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public int Shipping { get; set; }
        public int ShippingMethod { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<decimal> TotalPay { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual Shipping Shipping1 { get; set; }
        public virtual ShippingMethods ShippingMethods { get; set; }
    }
}
