//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public Pictures()
        {
            this.Colors = new HashSet<Colors>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string PicName { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<Colors> Colors { get; set; }
        public virtual Products Products { get; set; }
    }
}
