//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.CartProducts = new HashSet<CartProducts>();
            this.Colors = new HashSet<Colors>();
            this.OrderProducts = new HashSet<OrderProducts>();
            this.Pictures = new HashSet<Pictures>();
            this.Sizes = new HashSet<Sizes>();
            this.AttrContents = new HashSet<AttrContents>();
            this.FiltCatagories = new HashSet<FiltCatagories>();
        }
    
        public int ID { get; set; }
        public int Price { get; set; }
        public Nullable<int> NewPrice { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public bool IsNew { get; set; }
        public bool IsHot { get; set; }
        public bool IsDiscout { get; set; }
        public int SaleCount { get; set; }
        public int VisitCount { get; set; }
        public int BrandId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
    
        public virtual ICollection<CartProducts> CartProducts { get; set; }
        public virtual ICollection<Colors> Colors { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual ICollection<Pictures> Pictures { get; set; }
        public virtual ICollection<Sizes> Sizes { get; set; }
        public virtual ICollection<AttrContents> AttrContents { get; set; }
        public virtual ICollection<FiltCatagories> FiltCatagories { get; set; }
        public virtual Brand Brand { get; set; }
    }
}
